### ISSUE TITLE
Initial Project Home page screen shows blank projects

### ISSUE THREAD

**Issue by laurenyarrington** [miahuynhh/footnote#39]
Expected Behavior: When creating and logging into a new account, the home page should not display projects because it is a new account, only the button to create a new one. 

Steps to reproduce:
- Create a new account
- Log into the new account
- The home page appears with additional blank projects

I have determined that this issue can be fixed on the front end, in the UserHome.tsx file. 

This issue occurs every time; not a time-sensitive issue, but if addressed, will greatly improve the user experience

Device: MacBook Pro; OS: MacOS; Browser: Chrome

**Comment by miahuynhh** [comment]
mockannotations has been removed. no projects are shown now if a user doesn't have existing projects
