### ISSUE TITLE
Pressing enter on login/create account is not working

### ISSUE THREAD

**Issue by alsiu7** [miahuynhh/footnote#67]
Summary: (Enhancement/Suggestion)
Pressing enter when logging in or creating an account brings the user to an error page.

Component:
Frontend pages (Log in / Sign up page)

Version:
Beta release

Device, OS, Browser:
Surface 7, Windows 10, Chrome

Description:
When you press enter on your keyboard rather than the button on the page itself, it brings you to an error page. Not that big of an issue since you can just press the button to login or create account, but pressing enter should work as well.

**Comment by miahuynhh** [comment]
Thank you for pointing this out :)) Our beta release didn't include this functionality (Submit on Enter key press) but we are working on having this functionality work!

**Comment by miahuynhh** [comment]
Bug fixed! Enter key should work now.
