### ISSUE TITLE
No convenient way for going back to previous pages

### ISSUE THREAD

**Issue by alsiu7** [miahuynhh/footnote#69]
Summary: (Enhancement/Suggestion)
No functionality to go to a previous page.

Component:
Frontend pages (Log in / Sign up, Home, Project pages)

Version:
Beta release

Device, OS, Browser:
Surface 7, Windows 10, Chrome

Description:
After logging in or creating an account, there is no option on the page itself to log out. This could be a potential privacy risk(?)
After creating a new project, there is no option on the page itself to go back to home page. This could be convenient to add.

**Comment by miahuynhh** [comment]
Thank you for your feedback :) Our beta release didn't include a logout button and a navigation panel (to go back to the homepage) but will be incorporated for final release.
