### ISSUE TITLE
Viewing non-existent project pages through custom URL

### ISSUE THREAD

**Issue by alsiu7** [miahuynhh/footnote#73]
Summary: (Bug)
It is possible to enter a non-existent project page 

Component:
Backend projects API (?)

Version:
Beta release

Device, OS, Browser:
Surface 7, Windows 10, Chrome

Description:
Without creating any new projects, you can input any project number into the web browser and still view it 
(ex: `http://localhost:5173/project/1313`). Additionally, when going back to the home page, that project is not there.

**Comment by Purplecannon** [comment]
Addressed
