### ISSUE TITLE
Using Email as Username lead to 404 Error Page

### ISSUE THREAD

**Issue by YeonjunKo** [miahuynhh/footnote#74]
Summary: (Enhancement/Suggestion)
Using email as username when creating new account lead to 404 error page instead of accepting/warning the user input (whether it's valid or invalid)

Component:
Frontend pages (Log in / Sign up page)

Version:
Beta release

Device, OS, Browser:
Local Server

Description:
Not a big issue, but when using the email as username it brings to 404 page. If using email as username is invalid, it'll be better if there is a warning sign that asks user to put different username instead of leading to a error page.

**Comment by YeonjunKo** [comment]
Another issue: even after I use normal username without @ leads to Unexpected Application Error: possibly the error lies using Enter key instead of submit button?

**Comment by miahuynhh** [comment]
Yes, we are working on having the Enter key work rather than needing to press the submit button! If you just press the submit button, you can use your email to register normally! 
Please let us know if you can register normally using an email and then pressing the submit button

**Comment by miahuynhh** [comment]
Enter key is working instead of having to press Submit button!
